export VLLM_ATTENTION_BACKEND=XFORMERS

policy_path=/mnt/bn/seedllm3-lixuefeng-3/ckpts/Qwen/Qwen2.5-3B
rollout_batch_size=128
n_samples_per_prompts=16
episode=100
temperature=1.0
batch_size=64
lr=1e-6
kl_loss_coef=0
kl_coef=0
entropy_coeff=0
max_gen_length=8192
run_name=rl.grpo_qwen.1.5b_$(TZ='UTC-8' date "+%m%d_%H%M")
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=./data/train/train.parquet \
    data.val_files=./data/train/test.parquet \
    data.train_batch_size=$rollout_batch_size \
    data.val_batch_size=2048 \
    data.shuffle=True \
    data.max_prompt_length=400 \
    data.filter_overlong_prompts=True \
    data.max_response_length=$max_gen_length \
    actor_rollout_ref.model.path=$policy_path \
    actor_rollout_ref.actor.optim.lr=$lr \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=$batch_size \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=$kl_loss_coef \
    actor_rollout_ref.actor.entropy_coeff=$entropy_coeff \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.temperature=$temperature \
    actor_rollout_ref.rollout.top_p=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.90 \
    actor_rollout_ref.rollout.n=$n_samples_per_prompts \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=$kl_coef \
    trainer.logger=['console','wandb'] \
    trainer.project_name='ct_rl' \
    trainer.experiment_name=${run_name} \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=40 \
    trainer.test_freq=4 \
    trainer.resume_mode=auto \
    trainer.total_epochs=$episode $@